env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/eslint-config-prettier'
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - prettier
rules: {
  'vue/multi-word-component-names': 0,
}
